#Logger
logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    url: jdbc:mysql://mysql:3306/test
    username: root
    password: 1122q!
    driver-class-name: com.mysql.cj.jdbc.Driver
