spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1122q!
    driver-class-name: com.mysql.cj.jdbc.Driver
